### ISSUE TITLE
There is a new version

### ISSUE THREAD

**Issue by buntspexxxxt** [mbentley/docker-omada-controller#102]
Just saw that there is a new version (V4.3.5) from 2021-04-27.

**Comment by mbentley** [comment]
Thanks for the heads up; checking it out now.  My script apparently didn't pick up the new version.

**Comment by mbentley** [comment]
Actually, there is no 4.3.5 version for Linux; only Windows unless you have a link the shows otherwise.

**Comment by buntspexxxxt** [comment]
WTF...They must have pulled it for whatever reason. I still have the file in my Download folder ;-/

**Comment by mbentley** [comment]
OK, my monitor just triggered - they must have re-published 4.3.5.
