### ISSUE TITLE
Unable to pull v4.3 image using  "latest" tag.

### ISSUE THREAD

**Issue by jsn0327** [mbentley/docker-omada-controller#111]
I am  using Portainer to manage my Docker containers.  When I initially pulled down the Omada Controller image from your DockerHub, I used the 4.2 tag, which pulled down the latest v4.2 image.  Since the version is now 4.3, I can't figure out how to pull down the 4.3 image and apply it to the 4.2 container, so I would like to change the tag to "latest", which should avoid this issue in the future.  After creating a new container and trying to pull down the v4.3 image using the "latest" tag, I noticed (in the about section of the Omada controller) that even with the "latest" tag, it is still pulling down v4.2.11.  Is this an issue with your repo, or should I be doing something differently in order to pull down the latest version of the image; regardless of whether it is 4.2 or 4.3?  Below is the name of my current image (which pulled v4.2.11).  Thanks.

hub.docker.com/r/mbentley/omada-controller/latest:latest@sha256:7f179fda9ece676300a329a264993fdbecdfb314ecfe4410b07c76f8b3126784

**Comment by mbentley** [comment]
Working fine here:

```
$ docker pull mbentley/omada-controller:latest
latest: Pulling from mbentley/omada-controller
4bbfd2c87b75: Already exists
d2e110be24e1: Already exists
889a7173dcfe: Already exists
c1aeca99619c: Pull complete
8b4fd3b881a6: Pull complete
4e07c86776c2: Pull complete
Digest: sha256:d47c46eeafb0701045e89bb6bde2b2b92264011b3703a6de624ec1c2b75a2fc6
Status: Downloaded newer image for mbentley/omada-controller:latest
docker.io/mbentley/omada-controller:latest
```

```
docker run -d \
  --name omada-controller \
  --restart unless-stopped \
  -p 8088:8088 \
  -p 8043:8043 \
  -p 8843:8843 \
  -p 29810:29810 \
  -p 29810:29810/udp \
  -p 29811:29811 \
  -p 29811:29811/udp \
  -p 29812:29812 \
  -p 29812:29812/udp \
  -p 29813:29813 \
  -p 29813:29813/udp \
  -e MANAGE_HTTP_PORT=8088 \
  -e MANAGE_HTTPS_PORT=8043 \
  -e PORTAL_HTTP_PORT=8088 \
  -e PORTAL_HTTPS_PORT=8843 \
  -e SHOW_SERVER_LOGS=true \
  -e SHOW_MONGODB_LOGS=false \
  -e SSL_CERT_NAME="tls.crt" \
  -e SSL_KEY_NAME="tls.key" \
  -e TZ=Etc/UTC \
  -v omada-data:/opt/tplink/EAPController/data \
  -v omada-work:/opt/tplink/EAPController/work \
  -v omada-logs:/opt/tplink/EAPController/logs \
  mbentley/omada-controller:latest
```

![screenshot 2021-06-02 at 9 11 05 AM](https://user-images.githubusercontent.com/414445/120485851-7d487f00-c382-11eb-8dd1-525336b05adf.png)

Where did you get that digest of `sha256:7f179fda9ece676300a329a264993fdbecdfb314ecfe4410b07c76f8b3126784` from?
