### ISSUE TITLE
4.4.4 fails to build

### ISSUE THREAD

**Issue by mbentley** [mbentley/docker-omada-controller#127]
**Describe the bug**

#125 introduced 4.4.4 but something has changed in the install that is failing for all builds.

**To Reproduce**

1. foo
2. bar
3. baz
4. qux

**Expected behavior**

**How you're launching your container**

**Container Logs**

```
logs
go
here
```

**Additional context**

**Comment by codegeek** [comment]
Looks like the tar package added back the root dir `Omada_SDN_Controller_v4.4.4_linux_x64`

**Comment by mbentley** [comment]
I love the inconsistency of their builds 😮‍💨

**Comment by mbentley** [comment]
Should be fixed here in just a few minutes when the builds complete.
