### ISSUE TITLE
Container fails to run

### ISSUE THREAD

**Issue by woolmonkey** [mbentley/docker-omada-controller#130]
The container was working but got updated and now fails to start with this error.
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/entrypoint.sh": stat /entrypoint.sh: no such file or directory: unknown

**Comment by woolmonkey** [comment]
Saw this was already discussed.

**Comment by mbentley** [comment]
Happening right now?
