### ISSUE TITLE
Synology Setup

### ISSUE THREAD

**Issue by crgable** [mbentley/docker-omada-controller#137]
Do you have any sort of instructions for installation on Docker on a Synology NAS? I have the image set up and even copied the settings recommended here (https://www.epidemiology.tech/virtualization-containers/docker/tp-link-omada-controller-on-docker-in-synology-nas/) but I can't get anything to show up when I try to access the container via IP and port number. 
Can you help me?

**Comment by crgable** [comment]
I get a HTTP ERROR 404 when trying to access it...any direction you can provide would be helpful.

**Comment by christianbormann** [comment]
I use the following settings on my DS720+ and can access the website via https://[ip-of-synology]:8043

Ports:
![omada_ports](https://user-images.githubusercontent.com/8651970/141935428-ebc175a1-b223-4551-bb70-fd4acdaa0141.PNG)

Environment:
![omada_env](https://user-images.githubusercontent.com/8651970/141935425-ff362f5b-6e30-4507-84ee-a7ebd48d0e6b.PNG)

Volumes:
![omada_volume](https://user-images.githubusercontent.com/8651970/141935429-613dde2d-15ff-4f37-baa5-60cc556441ad.PNG)

**Comment by mbentley** [comment]
I'm not sure how Synology's implementation of Docker is different.  Might be better if you explain how you're running the container in Synology and how you're accessing it in your browser.

Most likely issue without knowing anything more: Don't try to map the ports to different ports via Docker unless you also set them via the environment variables as explained in the README.

**Comment by crgable** [comment]
![Screenshot 2021-11-16 080131](https://user-images.githubusercontent.com/94421467/141990087-d8d1c332-d78e-4937-adc3-d44c18ff9b3c.png)
Here are my current settings...

When I try to pull up the UI by typing http://192.168.1.2:49232/login I get the 404 error...all the other ports I tried pull up an invalid response. (ERR_SSL_PROTOCOL_ERROR)

**Comment by mbentley** [comment]
Yup, that's why.  The ports inside the container (listed in the "Container Port" column) must match the ones exposed on the host (listed in the "Local Port" column).  They must match.  If you do change them, you must use the environment variables that are shown there (the `*_PORT` variables) to match what you map them to.

It's just how the application is written that the behavior works that way.  Not 100% sure why it does that but that's what is required.

**Comment by crgable** [comment]
Ahh...that was it. The container defaults those ports to "auto" which means random numbers get assigned to them. Getting all the ports manually assigned to the same ones in the environmental variables fixed everything. Thank you for your help.

**Comment by mbentley** [comment]
Good deal.  I thought the error looked familiar 😄
