### ISSUE TITLE
Email notifications not working [fix included]

### ISSUE THREAD

**Issue by guitarmanusa** [mbentley/docker-omada-controller#142]
Bentley, HUGE thanks to you for this docker image.  There is actually a bug in the Omada Controller itself, well actually in the version of openjdk that TP link are using.  https://community.tp-link.com/en/business/forum/topic/267794?replyId=606514

Anyways, if you edit the java.security file "/etc/java-8-openjdk/security/java.security" and delete "TLSv1, TLSv1.1" from the list of disabled algorithms (line 704) and restart the controller it will fix email notifications (Settings -> Controller -> Mail Server).

I accomplished this by copying the java.security file to my workstation, editing it, and then uploading it back to the container:

$ docker cp omada-controller:/etc/java-8-openjdk/security/java.security .
edit line 704 in your favorite editor
$ docker cp java.security omada-controller:/etc/java-8-openjdk/security/java.security

It would be even MORE awesome if you could roll this fix into your docker image!  Then your container would be even better than the official release!

**Comment by mbentley** [comment]
You're in luck!  Set  the [environment variable](https://github.com/mbentley/docker-omada-controller#optional-variables)`TLS_1_11_ENABLED` to `true` and it will already do that.
