### ISSUE TITLE
Version 5.0.29 available

### ISSUE THREAD

**Issue by tophee** [mbentley/docker-omada-controller#154]
Just in case you haven't seen it: with some delay, TP-link have released version 5 of the Omada controller for Linux (after fixing some issues that Windows users reported). See https://community.tp-link.com/en/business/forum/topic/515912

Particularly interesting: 
> 3) Added DHCP Reservation in Services, allowing pre-configuration and support for reserving IP addresses outside the DHCP Range.

**Comment by tarfeef101** [comment]
Not sure where you see anything about the linux software controller there? Looks like updates for their hardware appliances to me

**Comment by tophee** [comment]
You are right, of course. Don't know what I was thinking.
