### ISSUE TITLE
connect failure list is empty

### ISSUE THREAD

**Issue by kipusoep** [mbentley/docker-omada-controller#167]
Hey!

Thanks for the docker image, really appreciate it!
I know this is not the Omada forum, but was wondering if any of you have the same.
Just upgraded to v5 and noticed a message is logged multiple times per minute:
`01-10-2022 11:14:47.501 INFO [https-jsse-nio-8043-exec-8] [] c.t.s.o.c.d.a.i(173): connect failure list is empty`
I know it's just an info message, but it is spamming the logs.

Any idea?

**Comment by mbentley** [comment]
I haven't seen that error message in my logs since upgrading the v5.  Not sure if it is related but I only use mine to control my  EAPs.
