### ISSUE TITLE
Unable to reach Login page (404 not found) 

### ISSUE THREAD

**Issue by CrAsH0v3r** [mbentley/docker-omada-controller#181]
**Describe the bug**
I have no way to reach de login page after setting the docker image using Portainer on a rasp 4+. 

It always says "Error 404 page not found" 

My issue is very similare to some recent issues but I did not manage to fix it with these explanations. 

**To Reproduce**

1. Installed Portainer and no issue to reach it. 
2. Create a Container with this image : [mbentley/omada-controller:latest-armv7l@sha256:b2641a48da6fbcf5b481a74f2a6e0a3f80af1f82b17487eb38a7e6f70bf35789](http://10.0.0.151:9000/#!/2/docker/images/sha256%3Ab2641a48da6fbcf5b481a74f2a6e0a3f80af1f82b17487eb38a7e6f70bf35789)  -> No custom settings, port fowarding etc. 
3. Start the container with no error
4. Try to reach the login page with many combination "Https/Http and port 8043/8088"

**Expected behavior**
Reach the login Page

**How you're launching your container**
Managed by Portainer, any way to find it?

**Container Logs**

      
INFO: Time zone set to 'Etc/UTC'
INFO: Starting Omada Controller as user omada
02-16-2022 16:00:09.116 INFO [log4j-thread] [] c.t.s.o.c.o.a.b(32): success to load configuration omada.properties
02-16-2022 16:00:09.201 INFO [main] [] c.t.s.o.s.OmadaBootstrap(79): going to start local mongod.
02-16-2022 16:00:40.761 INFO [main] [] c.t.s.o.s.s.b(161): mongodb process id is 39
02-16-2022 16:00:40.766 ERROR [main] [] c.t.s.f.c.FacadeUtils(68): facadeMsgEnable is not enable, msg: Mongo DB server started
02-16-2022 16:00:40.770 INFO [main] [] c.t.s.o.s.s.b(142): Mongo DB server started
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.3)
02-16-2022 16:00:43.761 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(55): Starting OmadaLinuxMain v5.0.30 using Java 1.8.0_292 on f7a36215b5a0 with PID 1 (/opt/tplink/EAPController/lib/local-starter-5.0.30.jar started by omada in /opt/tplink/EAPController/lib)
02-16-2022 16:00:43.772 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(660): No active profile set, falling back to default profiles: default
02-16-2022 16:01:06.026 WARN [main] [] o.s.d.c.CustomConversions(260): Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
02-16-2022 16:01:13.527 WARN [main] [] o.s.d.c.CustomConversions(260): Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
02-16-2022 16:01:28.427 INFO [main] [] c.t.s.l.c.s.d.CacheLogConsumeHandler(61): log mq consume task is start...
02-16-2022 16:01:28.437 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(61): Started OmadaLinuxMain in 46.334 seconds (JVM running for 82.197)
02-16-2022 16:01:29.064 INFO [main] [] c.t.s.o.s.d.a(78): Db unchanged. No need to compatible or init data.
02-16-2022 16:01:29.530 INFO [main] [] c.t.s.o.s.t.OmadacInitTask(149): succeed get default omadac OmadacVO(id=4fe9f22d8421b2d98de882fac595a58a, name=Omada Controller_95A58A)
02-16-2022 16:01:33.578 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(124): upgrade workGroup core thread num is 8, max thread num is 8
02-16-2022 16:01:33.698 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(151): upgradeSendReq workGroup core thread num is 8, max thread num is 8
02-16-2022 16:01:34.599 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(97): manager workGroup core thread  num is 16, max thread num is 16
02-16-2022 16:01:40.229 INFO [main] [] c.t.s.e.s.c.c(152): start schedule remove expire device... period = 10
02-16-2022 16:01:40.255 INFO [main] [] c.t.s.e.s.c.c(145): update rateLimiterCache, permitsPerSecond = 5.0
02-16-2022 16:01:44.568 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(70): adopt workGroup core thread num is 8, max thread num is8
02-16-2022 16:01:46.517 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(43): discovery workGroup core thread num is 2, max thread num is 10
02-16-2022 16:01:49.340 WARN [https-jsse-nio-8043-exec-5] [] o.s.d.c.CustomConversions(260): Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
02-16-2022 16:01:49.612 WARN [https-jsse-nio-8043-exec-5] [] o.s.d.c.CustomConversions(260): Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
02-16-2022 16:01:57.759 INFO [main] [] c.t.s.o.p.b.a.c(72): DisconnectRequestServer start
02-16-2022 16:01:58.914 INFO [main] [] c.t.s.o.d.g.a(124): discovery Port is 29810.
02-16-2022 16:01:58.915 INFO [main] [] c.t.s.o.d.g.a(125): manage    port v1 is 29811.
02-16-2022 16:01:58.916 INFO [main] [] c.t.s.o.d.g.a(126): manage    port v2 is 29814.
02-16-2022 16:01:58.916 INFO [main] [] c.t.s.o.d.g.a(127): adopt     port v1 is 29812.
02-16-2022 16:01:58.917 INFO [main] [] c.t.s.o.d.g.a(128): upgrade   port is 29813.
02-16-2022 16:01:59.017 INFO [main] [] c.t.s.e.t.a.t.AbstractServer(53): Start NettyUdpServer bind /0.0.0.0:29810, export localhost/127.0.0.1:29810
02-16-2022 16:01:59.055 INFO [main] [] c.t.s.e.t.n.NettyTcpServer(119): TCP server /0.0.0.0:29812 global traffic shaping, writeLimit: 518979584, readLimit: 0, checkInterval: 1000, max wait time: 15000
02-16-2022 16:01:59.084 INFO [main] [] c.t.s.e.t.a.t.AbstractServer(53): Start NettyTcpServer bind /0.0.0.0:29812, export localhost/127.0.0.1:29812
02-16-2022 16:01:59.087 INFO [main] [] c.t.s.e.t.n.NettyTcpServer(119): TCP server /0.0.0.0:29811 global traffic shaping, writeLimit: 518979584, readLimit: 0, checkInterval: 1000, max wait time: 15000
02-16-2022 16:01:59.090 INFO [main] [] c.t.s.e.t.a.t.AbstractServer(53): Start NettyTcpServer bind /0.0.0.0:29811, export localhost/127.0.0.1:29811
02-16-2022 16:01:59.139 INFO [main] [] c.t.s.e.t.n.NettyTcpServer(119): TCP server /0.0.0.0:29813 global traffic shaping, writeLimit: 518979584, readLimit: 0, checkInterval: 1000, max wait time: 15000
02-16-2022 16:01:59.143 INFO [main] [] c.t.s.e.t.a.t.AbstractServer(53): Start NettyTcpServer bind /0.0.0.0:29813, export localhost/127.0.0.1:29813
02-16-2022 16:01:59.147 INFO [main] [] c.t.s.e.t.n.NettyTcpServer(119): TCP server /0.0.0.0:29814 global traffic shaping, writeLimit: 518979584, readLimit: 0, checkInterval: 1000, max wait time: 15000
02-16-2022 16:01:59.150 INFO [main] [] c.t.s.e.t.a.t.AbstractServer(53): Start NettyTcpServer bind /0.0.0.0:29814, export localhost/127.0.0.1:29814
02-16-2022 16:01:59.151 ERROR [main] [] c.t.s.f.c.FacadeUtils(68): facadeMsgEnable is not enable, msg: Device connector server started.
02-16-2022 16:01:59.153 ERROR [main] [] c.t.s.f.c.FacadeUtils(68): facadeMsgEnable is not enable, msg: Omada Controller started
02-16-2022 16:01:59.153 INFO [main] [] c.t.s.o.s.t.SuccessExitTask(23): Omada Controller started

```
**Additional context**
Tried all the commands found in other threads.
curl -kvL https://10.0.0.201:8043 -> Connection refused
curl -kvL https://10.0.0.201:8088 -> Connetion refused
curl -kvL https://10.0.0.201:49218 -> Returns the login address, but unable to use it (https://10.0.0.201:49218/4fe9f22d8421b2d98de882fac595a58a/login)
curl -kvL http://10.0.0.201:49218 -> Connection requires TLS (OK)
curl -kvL http://10.0.0.201:49217 -> Returns the login address but not working ('http://10.0.0.201:49217/4fe9f22d8421b2d98de882fac595a58a/login)
 
EDIT: Just noticed the result of the command for port 49218 and 49217 : 

"Connected to 10.0.0.151 (10.0.0.151) port 49218 (#0)
* Expire in 0 ms for 6 (transfer 0xc4c8b0)
> GET /4fe9f22d8421b2d98de882fac595a58a/login HTTP/1.1
> Host: 10.0.0.151:49218
> User-Agent: curl/7.64.0
> Accept: */*
>
**< HTTP/1.1 404**
< Content-Length: 0
"

Any ideas?

Thanks in advance!

**Comment by mbentley** [comment]
So where are you getting ports 49217 & 49218 from?  Those look like they're in the ephemeral port range that Docker randomly assigns exposed ports that are not explicitly mapped.  Sounds like you're running into the problem described here; https://github.com/mbentley/docker-omada-controller#using-port-mapping

**Comment by CrAsH0v3r** [comment]
Tried to run it from command line like example in the linked page, and I get an error due to the fact I have an instance of influxdb already using port 8088. 

Will start by working on that..

**Comment by mbentley** [comment]
Yeah, and you can remap the ports for the Omada Controller; you just need to also update the controller's environment variables that reconfigures the ports internally since they have to match in the container to what they're mapped to on the host.

**Comment by CrAsH0v3r** [comment]
You can close ;)
Changed the influxdb port and restarted the service. Recreated the docker from command line, and it's working !

Thanks for quick help!
