### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by codersaur** [mbentley/docker-omada-controller#188]
Thanks for maintaining this project Matt. However, there have been several [updates to the image on dockerhub](https://hub.docker.com/r/mbentley/omada-controller/tags), yet I see no updates or releases on github. Am I missing something? Where can we see a change log?

**Comment by mbentley** [comment]
The images are re-build daily but buildkit caching is used so often there is no change.  The images will actually be rebuilt when:

- The image cache is unexpectedly busted (can happen somewhat randomly with buildkit but not often)
- The upstream base image is updated
- There are vulnerabilities in the base image and I proactively pre-patch them and repackage the base image
- There are vulnerabilities in the layers above the base image (e.g. - packages that get installed as dependencies)
- There is an update via PR to the repo

The multi-arch manifest lists are re-written daily though but that should basically be a no-op if the layers changed in any of the supported architectures.
