### ISSUE TITLE
Ubuntu 20.04 support for Omada Software Controller V5

### ISSUE THREAD

**Issue by markus-gitdev** [mbentley/docker-omada-controller#200]
**Is your feature request related to a problem? Please describe.**
Your docker image still uses Ubuntu 18.04, but regarding the information from [TP-Link](https://www.tp-link.com/us/support/download/omada-software-controller/#Controller_Software) Ubuntu 20.04 is also supported for V5 of their Omada Software Controller.

**Describe the solution you'd like**
It would be great if you could update the docker image to use Ubuntu 20.04.

**Comment by mbentley** [comment]
Just curious for understanding priority - any other specific needs beyond just that it isn't the latest Ubuntu?  I do plan on having it updated prior to the end of standard support for 18.04 which is April 2023 though.

**Comment by markus-gitdev** [comment]
No urgency.
I just wanted to draw attention to the topic, as Ubuntu is 2 LTS releases behind.

**Comment by mbentley** [comment]
Good deal. Just making sure you weren't doing anything like extending the image where a package from 20.04 was preferred.

**Comment by markus-gitdev** [comment]
That was fast! Thank you for the fast and smooth implementation.
