### ISSUE TITLE
Question - is it safe to let the omada controller update inside the container?

### ISSUE THREAD

**Issue by iampegram** [mbentley/docker-omada-controller#204]
I got a notification to update the controller software inside the container. Is it safe to use this method, or should I back up and restore inside an updated container?

**Comment by mbentley** [comment]
Updating from within the controller will probably result in upgraded persistent data but if the container is re-created, it will be reverted to the previous version.

Unless specifically specified in the release notes, like in 3.x to 4.x, you can just stop, remove, and re-create the container with the newer version and the software will handle the data migrations.

**Comment by iampegram** [comment]
That worked, thanks for all the work you've put into this!
