### ISSUE TITLE
Container keeps restarting after upgrade from 4.8 to latest - hard coded java settings in old container folder-data?

### ISSUE THREAD

**Issue by MRCLVSTR** [mbentley/docker-omada-controller#205]
I have been using Docker Omada container version 4.8 on a Synology NAS for about 5 months and it worked flawlessly. Since I was not able to install SMTP successfully, I tried to install the :latest image. When starting this image crashes immediately with the following error 
<<<<<<<
message:
############################
WARNING: CMD from 4.x detected!  It is likely that this container will fail to start properly with a "Could not find or load main class com.tplink.omada.start.OmadaLinuxMain" error!
  See the note on old CMDs at https://github.com/mbentley/docker-omada-controller#upgrade-issues for details on why and how to resolve the issue.
############################
INFO: Starting Omada Controller as user omada
Error: Could not find or load main class com.tplink.omada.start.OmadaLinuxMain
>>>>>>>

This error has been reported on a few places, e.g.:
- https://github.com/mbentley/docker-omada-controller#upgrade-issues
- https://github.com/mbentley/docker-omada-controller/issues/57 
- https://githubhot.com/repo/mbentley/docker-omada-controller/issues/174

Turns out to be a problem specific for Synology NAS (is this true??) where java-settings are stored in the container data, overruling CMD parameters used when creating the new container. So the suggestion is to remove the old container and all it's folders (data/logs/work) and recreate the container from scratch, initially losing all Omada setting and history.

My question: How to best import the settings and history from the old container (v4.8)?
Can I best import settings created using backup option in the Omade controler website (Settings -> Maintenance -> Backup & Restore), or is there a better way to refill the newly recreated container data? Reusing data/logs/work folders doesn't sound like an option given the hardcoded java-information...

Thanks for answer!!

Marcel

**Comment by mbentley** [comment]
I just updated the message in the known issues markdown and fixed the now incorrect URL.  Let me know if what is in master is more clear now.

**Comment by MRCLVSTR** [comment]
Thanks for taking the time & effort, highly appreciated.
That's exactly what I thought I did while getting the error message, but will try again using your instructions and come back to you this weekend if not successful or having suggestions to improve your markdown.

**Comment by MRCLVSTR** [comment]
Installation went successful when recreating the container (leaving the data files in place), which means i got the traditional login page and was able to login on the Omada website (instead of starting initialisation from scratch). I used command below, specific for Synology NAS (not using certificate on local network).

  --restart unless-stopped \
  -p 8088:8088 \
  -p 8043:8043 \
  -p 8843:8843 \
  -p 29810:29810/udp \
  -p 29811:29811 \
  -p 29812:29812 \
  -p 29813:29813 \
  -p 29814:29814 \
  -e MANAGE_HTTP_PORT=8088 \
  -e MANAGE_HTTPS_PORT=8043 \
  -e PORTAL_HTTP_PORT=8088 \
  -e PORTAL_HTTPS_PORT=8843 \
  -e SHOW_SERVER_LOGS=true \
  -e SHOW_MONGODB_LOGS=false \
  -e TZ=Etc/CEST \
  -v /volume1/docker/omada/data:/opt/tplink/EAPController/data \
  -v /volume1/docker/omada/work:/opt/tplink/EAPController/work \
  -v /volume1/docker/omada/logs:/opt/tplink/EAPController/logs \
  mbentley/omada-controller:latest
 

However after login on the controller website, the Omada software started a "reinitialisation" by itself, taking quite a while and slowly breaking down my netwerk. Since I had other family member complaining, I did not allow the initialisation to finish, stopped the new container and reverted back to the older 4.8 version. After installing the old version and data-folders, I also had to switch off/on the router and accesspoint due to "missing heartbeat" errors. I assume this is Omada software functionality (not really something you can do about it), so I will have to give it a try again on a quite moment when nobody is at home... Wondering if others have experienced the same problem or just me messing up.

**Comment by mbentley** [comment]
Hard to say what is going on - the logs would probably provide some detail of what is going on.
