### ISSUE TITLE
[RE-OPEN] typo on --publish 29180 UDP port 

### ISSUE THREAD

**Issue by proap** [mbentley/docker-omada-controller#21]
Sorry for re-openning the ticket.
What I meant, was that in your docker script launch you have a typo:

>  -p 29810:29180/udp \

as the documentation mentions it, the port UDP 29810 should be open for EAP discovery. So I think the paramenter should be:

>  -p 29810:29810/udp \

otherwise, the port UDP29810 is being NATed to the port 29180 on the container which isn't listenning.
s

**Comment by mbentley** [comment]
Ah, thanks, I didn't catch that!  Fixed.
