### ISSUE TITLE
After update and reinstallation, no device forund

### ISSUE THREAD

**Issue by Chiller2019** [mbentley/docker-omada-controller#218]
**Describe the bug**
After a update, I cant reach any devices, I installed the docker-container from zero (remove container + volumes) and now, I cant reach any devices.

![Device](https://user-images.githubusercontent.com/50303399/180112391-73246978-385e-4b6a-9ba0-f61d7a388a22.jpg)

**Expected behavior**
```
docker run -d \
--name Omada-Controller \
--restart unless-stopped \
--net host \
-e MANAGE_HTTP_PORT=8088 \
-e MANAGE_HTTPS_PORT=8043 \
-e PORTAL_HTTP_PORT=8088 \
-e PORTAL_HTTPS_PORT=8843 \
-e SHOW_SERVER_LOGS=true \
-e SHOW_MONGODB_LOGS=false \
-e SSL_CERT_NAME="tls.crt" \
-e SSL_KEY_NAME="tls.key" \
-e TZ=Etc/UTC \
-v omada-data:/opt/tplink/EAPController/data \
-v omada-work:/opt/tplink/EAPController/work \
-v omada-logs:/opt/tplink/EAPController/logs \
mbentley/omada-controller:latest
```

**Additional context**
- Setup: OPNsense -> Proxmox (static IP to LAN_1)-> LXC (VLAN:12, Firewall: all allowed) -> Docker -> Omada
- I can reach WebInterfaces from Switch/AP
- Automatic update from watchdog
- On my local install Omada Controller, the devices are found, same LAN settings.

![Omada](https://user-images.githubusercontent.com/50303399/180112262-96cbf2c7-aa92-44d0-995f-ddb31f4674c3.jpg)

- Ping from Container says I can ping my devices, netcat says the ports UDP are open and reachable.

![Ping](https://user-images.githubusercontent.com/50303399/180113488-10fc22a2-8037-4a61-ac72-0e3ca05c60ee.jpg)
![TCP](https://user-images.githubusercontent.com/50303399/180114169-bdca7a5e-c870-4fd2-9439-abe60622387b.jpg)

Any ideas? Problem with the update? I'm to dumb?

**Comment by mbentley** [comment]
Do you know what version were you running previously?  Are you sure your devices are supported in the version of the controller you've upgraded to?

**Comment by Chiller2019** [comment]
> Do you know what version were you running previously? Are you sure your devices are supported in the version of the controller you've upgraded to?

Yeahr, 5.3.1 (like local Controller) and the Devices are up.

I use EAP225 V3 and SG2008 V4

**Comment by Chiller2019** [comment]
Ok, 21.07.2022, new LXC-Container without VLAN, no devices up.
It must be a failure on the Docker-Container. Idk why.....

I think, next step is to create directly from TP-Link Image a installation.

**Comment by mbentley** [comment]
So are you trying to cross VLANs between the controller and the devices you want to connect?  I am not sure what sort of discovery mechanism is being used but maybe that's the issue if you're crossing VLANs with devices.  I'm less of an expert on the Omada Controller software so take what I say there with a grain of salt.

**Comment by Chiller2019** [comment]
> So are you trying to cross VLANs between the controller and the devices you want to connect? I am not sure what sort of discovery mechanism is being used but maybe that's the issue if you're crossing VLANs with devices. I'm less of an expert on the Omada Controller software so take what I say there with a grain of salt.

Yeahr, in the first Setup and its worked.
But in the Test-Setup on the **same** Interfaces like Devices, without VLAN, it doesn't work either. That's what I don't understand. My local Controller works, find the devices, same Network like Devices. Thats very confused and idk what happend.

**Comment by Chiller2019** [comment]
Ok, now its confirmed.
A LXC without VLAN with a standalone Controller (Omada_SDN_Controller_V5.3.1_Linux_x64.deb) find the Devices.

**Its 100% docker or this image ...**
