### ISSUE TITLE
[Bug]: LInk Aggregation option for Omada Switches

### ISSUE THREAD

**Issue by banquer** [mbentley/docker-omada-controller#257]
### Describe the Bug

There is no way to edit a port in a switch supported device to make a LAG group with link aggregation.

### Expected Behavior

When a port in the supported swtich is selected and after click edit, a option under operation must appear, and you can select aggregating to select another switch port to be aggregated in the lag group.

### Steps to Reproduce

-Select switch device.
-Click in ports.
- Select one port.
- Click edit selected.
- No aggregation options appears.

### How You're Launching the Container

```plain
docker run -d --name=omada-controller \
-e PUID=1026 \
-e PGID=100 \
-e TZ=Europe/Madrid \
-e MANAGE_HTTP_PORT=8088 \
-e MANAGE_HTTPS_PORT=8043 \
-e PORTAL_HTTP_PORT=8088 \
-e PORTAL_HTTPS_PORT=8043 \
-e SHOW_SERVER_LOGS=true \
-e SHOW_MONGODB_LOGS=false \
-e SSL_CERT_NAME="tls.crt" \
-e SSL_KEY_NAME="tls.key" \
-v /volume1/docker/omada/data:/opt/tplink/EAPController/data \
-v /volume1/docker/omada/logs:/opt/tplink/EAPController/logs \
-v /volume1/docker/omada/work:/opt/tplink/EAPController/work \
--net host \
--restart always \
mbentley/omada-controller
```

### Container Logs

```plain
No logs about
```

### Additional Context

I put a link to tp-link community where the screen that must appers is shown.

https://community.tp-link.com/en/business/forum/topic/265184

**Comment by mbentley** [comment]
Not sure if there is anything I can personally do - this is definitely a software related issue so the forums would be the right place for this.
