### ISSUE TITLE
[Feature]: Include stop_grace_period in docker-compose template

### ISSUE THREAD

**Issue by phipolis** [mbentley/docker-omada-controller#260]
### What problem are you looking to solve?

After reading the [mongodb-corruption](https://github.com/mbentley/docker-omada-controller/blob/master/KNOWN_ISSUES.md#mongodb-corruption) section of known issues, recommending overriding docker's default 10-second stop timeout, I went looking for a way to ensure docker waited long enough for the controller to shut down cleanly.

### Describe the solution that you have in mind

At least for docker-compose users, there is the [stop_grace_period](https://docs.docker.com/compose/compose-file/#stop_grace_period) directive.

Could something like `stop_grace_period: 1m30s` be included in the template, so anyone who uses it will be protected from Docker killing the container too early by default?

**Comment by mbentley** [comment]
Nice, I didn't know that was a thing!
