### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by Mitulica** [mbentley/docker-omada-controller#269]
### What problem are you looking to solve?

Seems to be compiled only for ARM architectures. Would like to have support for Intel as well.

### Additional Context

Trying to run in QNAP Intel NAS Container Station app

**Comment by mbentley** [comment]
That's not true.  This is build for the following architectures: amd64 (which is not unique to AMD, it's Intel 64 bit as well), arm64, and (while not recommended) armv7l.  Where are you seeing that it is not available for Intel?
