### ISSUE TITLE
[Bug]: ERROR: failed to solve: mbentley/ubuntu:18.04: no match for platform in manifest

### ISSUE THREAD

**Issue by andreagx** [mbentley/docker-omada-controller#307]
### Controller Version

v3.2

### Describe the Bug

During build on ARM (Raspberry Pi Armv61) docker return an error

command ran:
docker build --platform linux/arm/v7 --build-arg INSTALL_VER="3.2" --build-arg ARCH="armv7l" --build-arg BASE="ubuntu:16.04" -f Dockerfile.v3.2.x -t mbentley/omada-controller:3.2-armv7l .

Error received:

=> ERROR [2/7] RUN   echo "**** Install Dependencies ****" &&  apt-get update &&  DEBIAN_FRONTEND="noninteractive" apt-get install -y gosu net-tools tzdata wget &&  rm -rf /  16.2s
------
 > [2/7] RUN   echo "**** Install Dependencies ****" &&  apt-get update &&  DEBIAN_FRONTEND="noninteractive" apt-get install -y gosu net-tools tzdata wget &&  rm -rf /var/lib/apt/lists/* &&  echo "**** Download Omada Controller ****" &&  cd /tmp &&  wget -nv "https://static.tp-Error received:
=> ERROR [2/7] RUN   echo "**** Install Dependencies ****" &&  apt-get update &&  DEBIAN_FRONTEND="noninteractive" apt-get install -y gosu net-tools tzdata wget &&  rm -rf /  16.2s
------
 > [2/7] RUN   echo "**** Install Dependencies ****" &&  apt-get update &&  DEBIAN_FRONTEND="noninteractive" apt-get install -y gosu net-tools tzdata wget &&  rm -rf /var/lib/apt/lists/* &&  echo "**** Download Omada Controller ****" &&  cd /tmp &&  wget -nv "https://static.tp-link.com/upload/software/2022/202208/20220818/Omada_Controller_v3.2.17_Linux_x64.tar.gz" &&  echo "**** Extract and Install Omada Controller ****" &&  tar zxvf Omada_Controller_v3.2.17_Linux_x64.tar.gz &&  rm Omada_Controller_v3.2.17_Linux_x64.tar.gz &&  cd Omada_Controller_* &&  mkdir /opt/tplink/EAPController -vp &&  cp bin /opt/tplink/EAPController -r &&  cp data /opt/tplink/EAPController -r &&  cp properties /opt/tplink/EAPController -r &&  cp webapps /opt/tplink/EAPController -r &&  cp keystore /opt/tplink/EAPController -r &&  cp lib /opt/tplink/EAPController -r &&  cp install.sh /opt/tplink/EAPController -r &&  cp uninstall.sh /opt/tplink/EAPController -r &&  cp jre /opt/tplink/EAPController/jre -r &&  chmod 755 /opt/tplink/EAPController/bin/* &&  chmod 755 /opt/tplink/EAPController/jre/bin/* &&  echo "**** Cleanup ****" &&  cd /tmp &&  rm -rf /tmp/Omada_Controller*:
------link.com/upload/software/2022/202208/20220818/Omada_Controller_v3.2.17_Linux_x64.tar.gz" &&  echo "**** Extract and Install Omada Controller ****" &&  tar zxvf Omada_Controller_v3.2.17_Linux_x64.tar.gz &&  rm Omada_Controller_v3.2.17_Linux_x64.tar.gz &&  cd Omada_Controller_* &&  mkdir /opt/tplink/EAPController -vp &&  cp bin /opt/tplink/EAPController -r &&  cp data /opt/tplink/EAPController -r &&  cp properties /opt/tplink/EAPController -r &&  cp webapps /opt/tplink/EAPController -r &&  cp keystore /opt/tplink/EAPController -r &&  cp lib /opt/tplink/EAPController -r &&  cp install.sh /opt/tplink/EAPController -r &&  cp uninstall.sh /opt/tplink/EAPController -r &&  cp jre /opt/tplink/EAPController/jre -r &&  chmod 755 /opt/tplink/EAPController/bin/* &&  chmod 755 /opt/tplink/EAPController/jre/bin/* &&  echo "**** Cleanup ****" &&  cd /tmp &&  rm -rf /tmp/Omada_Controller*:
------

### Expected Behavior

Armv71 should be run on Armv61? 

### Steps to Reproduce

launch on arm rpi 

### How You're Launching the Container

```plain
not applicable
```

### Container Logs

```plain
no logs in this phase
```

**Comment by mbentley** [comment]
So if you have a Raspberry Pi that runs armv6l and is actually armv6l, it's probably not going to be powerful enough to run a controller ([pi devices based on architecture](https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications)).  [With older Raspberry Pi devices with limited RAM, you will have issues running MongoDB and the SpringBoot app](https://github.com/mbentley/docker-omada-controller/blob/master/KNOWN_ISSUES.md#low-resource-systems) with limited RAM.   If you tell it to use the armv7l platform, it's also not going to be powerful enough to run qemu to emulate armv7l.  The [`ubuntu:16.04` image on Docker Hub](https://hub.docker.com/_/ubuntu/tags?page=1&name=16.04) doesn't have any armv6l architecture manifests so that won't work.

Could you describe what exactly you want to do from an outcome standpoint like what OS you're running, what architecture you're on?  Or just providing some information on your architecture and OS would be helpful:

* `cat /sys/firmware/devicetree/base/model`
* `dpkg --print-architecture`
* `uname -m`
* `cat /etc/os-release`
* `docker info`

**Comment by mbentley** [comment]
FYI, it does build and it does run.  It's gonna use a lot of RAM so you're probably gonna be swapping like mad, if you have swap.

```
$ docker stats --no-stream agitated_shtern
CONTAINER ID   NAME              CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O         PIDS
056c07239e08   agitated_shtern   7.09%     659MiB / 5.804GiB   11.09%    1.09kB / 0B   81.9kB / 43.2MB   65
```

**Comment by mbentley** [comment]
It has been a while since I have looked at 3.2.x but I am not sure if there are any tricks to keeping memory consumption lower but I am almost certain that would have to be something MongoDB side.  Even setting Xmx to 256, the container is consuming over 460 MB of RAM just after start up.

**Comment by mbentley** [comment]
For completeness, here is the Dockerfile: https://gist.github.com/mbentley/b99d5cba2dc284978be50dc3d50fbe88

**Comment by andreagx** [comment]
hello,

building ok, but I can't run image


[+] Building 2426.0s (12/12) FINISHED

docker images
REPOSITORY                  TAG          IMAGE ID       CREATED          SIZE
mbentley/omada-controller   3.2-armv6l   853c58038ede   55 minutes ago   466MB
hello-world                 latest       de23d9589845   6 days ago       8.95kB


$ docker run mbentley/omada-controller
Unable to find image 'mbentley/omada-controller:latest' locally
latest: Pulling from mbentley/omada-controller
docker: no matching manifest for linux/arm/v6 in the manifest list entries.

________________________________
Da: Matt Bentley ***@***.***>
Inviato: martedì 9 maggio 2023 21:28
A: mbentley/docker-omada-controller ***@***.***>
Cc: andreagx ***@***.***>; Author ***@***.***>
Oggetto: Re: [mbentley/docker-omada-controller] [Bug]: ERROR: failed to solve: mbentley/ubuntu:18.04: no match for platform in manifest (Issue #307)


For completeness, here is the Dockerfile: https://gist.github.com/mbentley/b99d5cba2dc284978be50dc3d50fbe88

**Comment by mbentley** [comment]
You would need to run `mbentley/omada-controller:3.2-armv6l` not `mbentley/omada-controller`.

**Comment by andreagx** [comment]
Tjank you for your reply
You're right sorry 🙂

Ok is started, but I can't reach http or https port. Port scanner says only the port 22 is opened. 🙁

WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm/v6) and no specific platform was requested
INFO: Validating user/group (omada:omada) exists with correct UID/GID (508:508)
INFO: Group (omada) doesn't exist; creating
INFO: User (omada) doesn't exist; creating
INFO: Time zone set to 'Etc/UTC'
WARN: ownership not set correctly on '/opt/tplink/EAPController/data'; setting correct ownership (omada:omada)
WARN: ownership not set correctly on '/opt/tplink/EAPController/logs'; setting correct ownership (omada:omada)
WARN: ownership not set correctly on '/opt/tplink/EAPController/work'; setting correct ownership (omada:omada)
WARN: permissions are not set correctly on '/tmp' (777); setting correct permissions (1777)
mode of '/tmp' changed from 0777 (rwxrwxrwx) to 1777 (rwxrwxrwt)
INFO: userland/kernel check passed
INFO: Starting Omada Controller as user omada
SLF4J: com.tp_link.eap.configuration.b
SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: com.tp_link.eap.util.o
startup...
May 10, 2023 6:41:27 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 4.3.1.Final

Omada Controller started

________________________________
Da: Matt Bentley ***@***.***>
Inviato: mercoledì 10 maggio 2023 20:34
A: mbentley/docker-omada-controller ***@***.***>
Cc: andreagx ***@***.***>; Author ***@***.***>
Oggetto: Re: [mbentley/docker-omada-controller] [Bug]: ERROR: failed to solve: mbentley/ubuntu:18.04: no match for platform in manifest (Issue #307)


You would need to run mbentley/omada-controller:3.2-armv6l not mbentley/omada-controller.

**Comment by mbentley** [comment]
You still have to run the software in the container [as documented in the README](https://github.com/mbentley/docker-omada-controller#using-port-mapping).  Look at the section under `Example usage for 3.2`

```
docker run -d \
  --name omada-controller \
  --restart unless-stopped \
  --ulimit nofile=4096:8192 \
  -p 8088:8088 \
  -p 8043:8043 \
  -p 8843:8843 \
  -p 29810:29810/udp \
  -p 29811:29811 \
  -p 29812:29812 \
  -p 29813:29813 \
  -p 29814:29814 \
  -e MANAGE_HTTP_PORT=8088 \
  -e MANAGE_HTTPS_PORT=8043 \
  -e SMALL_FILES=false \
  -e SSL_CERT_NAME="tls.crt" \
  -e SSL_KEY_NAME="tls.key" \
  -e TZ=Etc/UTC \
  -v omada-data:/opt/tplink/EAPController/data \
  -v omada-work:/opt/tplink/EAPController/work \
  -v omada-logs:/opt/tplink/EAPController/logs \
  mbentley/omada-controller:3.2-armv6l
```

**Comment by andreagx** [comment]
Thank you for the support, I'm new on Docker 🙂
So now works, I had to increase swap to 2048 MB. CPU is always high, but all in all the controller is not no too slow to use

________________________________
Da: Matt Bentley ***@***.***>
Inviato: mercoledì 10 maggio 2023 21:45
A: mbentley/docker-omada-controller ***@***.***>
Cc: andreagx ***@***.***>; Author ***@***.***>
Oggetto: Re: [mbentley/docker-omada-controller] [Bug]: ERROR: failed to solve: mbentley/ubuntu:18.04: no match for platform in manifest (Issue #307)


You still have to run the software in the container as documented in the README<https://github.com/mbentley/docker-omada-controller#using-port-mapping>. Look at the section under Example usage for 3.2

docker run -d \
  --name omada-controller \
  --restart unless-stopped \
  --ulimit nofile=4096:8192 \
  -p 8088:8088 \
  -p 8043:8043 \
  -p 8843:8843 \
  -p 29810:29810/udp \
  -p 29811:29811 \
  -p 29812:29812 \
  -p 29813:29813 \
  -p 29814:29814 \
  -e MANAGE_HTTP_PORT=8088 \
  -e MANAGE_HTTPS_PORT=8043 \
  -e SMALL_FILES=false \
  -e SSL_CERT_NAME="tls.crt" \
  -e SSL_KEY_NAME="tls.key" \
  -e TZ=Etc/UTC \
  -v omada-data:/opt/tplink/EAPController/data \
  -v omada-work:/opt/tplink/EAPController/work \
  -v omada-logs:/opt/tplink/EAPController/logs \
  mbentley/omada-controller:3.2-armv6l

**Comment by mbentley** [comment]
I would definitely enable auto-backups, keeping occasional backups off the device and be cautious about the swap - it can (and most likely will eventually) kill the SD card!

**Comment by andreagx** [comment]
Really I have an Oc200,  was for study purpose. I don’t think to use it



Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

Da: Matt ***@***.***>
Inviato: giovedì 11 maggio 2023 16:01
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [mbentley/docker-omada-controller] [Bug]: ERROR: failed to solve: mbentley/ubuntu:18.04: no match for platform in manifest (Issue #307)


I would definitely enable auto-backups, keeping occasional backups off the device and be cautious about the swap - it can (and most likely will eventually) kill the SD card!

**Comment by mbentley** [comment]
Let me know if I can help further.
