### ISSUE TITLE
[Bug]: Migration

### ISSUE THREAD

**Issue by vjwizkid6** [mbentley/docker-omada-controller#326]
### Controller Version

5.9.31

### Describe the Bug

Hi trying to work out the migration off the docker controller on to a newOC200 but cant for the life of me find the Migration tool in the docker controller. 

### Expected Behavior

To be able to run the Migration tool

### Steps to Reproduce

go to settinng and find the Migration tool

### How You're Launching the Container

```plain
na
```

### Container Logs

```plain
na
```

**Comment by mbentley** [comment]
Does the controller backup and restore not work?

**Comment by vjwizkid6** [comment]
Cant find a backup option. Where should it be

**Comment by mbentley** [comment]
I take that back - you have two options.  Backup and Restore or use the built in migration wizard.

## Migration

Settings > Migration and use the `Controller Migration` option.  I've never used this so I don't know anything after that.

## Backup and Restore

Settings > Maintenance and it's right at the top.

**Comment by vjwizkid6** [comment]
Thanks dont seam to have that option. I have a hunch that i am not lodged on as the master admin. Just need to work out what that was set to.

**Comment by vjwizkid6** [comment]
So i wasn't loged on as admin. All sorted now thanks for the help.
