### ISSUE TITLE
new upstream release 3.2.10

### ISSUE THREAD

**Issue by mbiebl** [mbentley/docker-omada-controller#33]
See
https://static.tp-link.com/2020/202004/20200420/Omada_Controller_v3.2.10_linux_x64.tar.gz

btw: I'm not sure if this is helpful or not (as you are monitoring this on your own).
If not, please say so, I won't mind.

**Comment by mbentley** [comment]
Thanks!  I only look at it every once and a while manually.  I had previously tried to scrape the screen but I wasn't successful.

**Comment by mbentley** [comment]
Fixed in #34
