### ISSUE TITLE
[Feature] Version Tag Repo for Omada Versions: 

### ISSUE THREAD

**Issue by ancoleman** [mbentley/docker-omada-controller#331]
### What problem are you looking to solve?

The repo has version support for Omada 3.0-5.9. To better make your repo tidy, would it be possible to start fresh with git tags each time you bump Omada version support? This way your not having to generate new docker files for each version, you have a single one, and a user can pull that specific git tag version for the corresponding omada version they are attempting to use?

### Describe the solution that you have in mind

Git Tags/Releases to correspond to Omada versioning.

**Comment by mbentley** [comment]
If I actually had anything outside of the packaging in the repo, such as actual app code, I might consider doing something different but at this point, I am not sure if there is really much of a benefit to changing anything.

If all I do would be to create tags, I would still have to update Dockerfiles when a new version is created so I am not really sure where any cleanup would occur.  Now I would be open to adding tags when a new version is released if that would somehow help.

If I went with just going back in history for specific git tags, it would actually just complicate the image build process on my end and probably just end up making more manual work so I am hesitant to do that.  If I we were to do a branching + tagging strategy, it would also just obfuscate the versions so it's trading off the complexity of having all of the files in one branch vs having them individually.

I would be more likely to create sub directories for each version before going down the route of branches or git tags but there are still common scripts to multiple versions which just complicates things from a build process.
