### ISSUE TITLE
[Feature]: Gateway Device Info Download port

### ISSUE THREAD

**Issue by dli417** [mbentley/docker-omada-controller#338]
### What problem are you looking to solve?

Thank you for quickly updating the docker image for the newly released Omada Controller version 5.12.7. In the changelog for this version (https://static.tp-link.com/upload/software/2023/202309/20230920/Linux%20Release%20Note.pdf), under New Features, it mentions the following: “Device Info Download: Introduced the ability to download device info of the Gateway. To access the feature, open the sidebar of Gateway, navigate to Config > Manage Device, and click Download. Omada Controller uses TCP port 29815 to receive device info.”

Should port 29815 be added to the GitHub repo README.md as a port mapping or environment variable?

### Describe the solution that you have in mind

Add port 29815 as a configurable docker compose port to enable the new Device Info Download feature.

**Comment by mbentley** [comment]
Ah, yes it should.  Good catch.

**Comment by mbentley** [comment]
Looking at the properties file, I also see there is a `port.rtty=29816` port mentioned that apparently became available in v5.9 according to https://www.tp-link.com/us/support/faq/3281/

**Comment by ProsperAdmin** [comment]
They were already an exposed port mapping since #309 ...

**Comment by mbentley** [comment]
Exposing ports from the container is one thing but I added support for modifying the ports via the properties file if one needs to.
