### ISSUE TITLE
[Feature]: Update Controller to v5.13.23

### ISSUE THREAD

**Issue by obsidiangroup** [mbentley/docker-omada-controller#397]
### What problem are you looking to solve?

Would like to see a container with the 5.13.23 release available.

**Comment by mbentley** [comment]
Where are you seeing a 5.13.23?  I only see 5.13.22.

**Comment by sutram** [comment]
I saw it in the controller UI and was able to down the tarball.

Omada_SDN_Controller_v5.13.23_linux_x64_20231228194009_1705039261727.tar.gz

**Comment by obsidiangroup** [comment]
When I logged into my controller instance, it prompted me to upgrade and like @sutram was able to download the tar.  But when going directly to the omada site, I could not locate it.

**Comment by obsidiangroup** [comment]
I've built the container locally with the 5.13.23 version.  Everything seems stable but will report back in a day or so.
![image](https://github.com/mbentley/docker-omada-controller/assets/54423468/042e4856-9f57-4230-b093-5e752c82f623)

**Comment by mbentley** [comment]
It has finally been published (see #400).  Closing in favor of that for now.  Will get the new version published this morning.

**Comment by mbentley** [comment]
The new version has been released.

**Comment by javito1081** [comment]
im using docker compose but i dont know how to update to 5.13.23 :-( i tried stopping the docker compose and remove the image then restart the docker compose and is still not updating, can someone please tell me the procedure im missing?
