### ISSUE TITLE
Cannot access the login page on a Synology NAS

### ISSUE THREAD

**Issue by AlexanderSanchezNL** [mbentley/docker-omada-controller#44]
I've tried to find the answer all over the Internet, but unfortunately I cannot find a solution for my problem: I get a ERR_CONNECTION_REFUSED when I try to open the Omada Controller on my Synology NAS. I use the NAS IP on my local LAN and port 8043 for https (8088 on http also doesn't work). Am I doing something wrong here?

I have a Synology DS718+ and I installed Docker + your Omada controller (latest version). The installation went smoothly and I don't see any errors in the logs. It's just that my browser connection is being refused. I assume I do not need to use the 172.17.0.0 network to access the Controller?

btw: I disabled the Firewall on the NAS to be sure.

Can you help me?

Below the exported config:
{
   "cap_add" : null,
   "cap_drop" : null,
   "cmd" : "/opt/tplink/EAPController/jre/bin/java -server -Xms128m -Xmx1024m -XX:MaxHeapFreeRatio\\=60 -XX:MinHeapFreeRatio\\=30 -XX:+HeapDumpOnOutOfMemoryError -XX:-UsePerfData -Deap.home\\=/opt/tplink/EAPController -cp /opt/tplink/EAPController/lib/*: com.tp_link.eap.start.EapLinuxMain",
   "cpu_priority" : 50,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enabled" : true,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      }
   ],
   "exporting" : false,
   "id" : "a23e6f0a44868105d498a643fadd5d028b823da0b1ae1e453034cc7d213fe499",
   "image" : "mbentley/omada-controller:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "mbentley-omada-controller",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 27001,
         "host_port" : 0,
         "type" : "udp"
      },
      {
         "container_port" : 27002,
         "host_port" : 0,
         "type" : "tcp"
      },
      {
         "container_port" : 29810,
         "host_port" : 0,
         "type" : "udp"
      },
      {
         "container_port" : 29811,
         "host_port" : 0,
         "type" : "tcp"
      },
      {
         "container_port" : 29812,
         "host_port" : 0,
         "type" : "tcp"
      },
      {
         "container_port" : 29813,
         "host_port" : 0,
         "type" : "tcp"
      },
      {
         "container_port" : 8043,
         "host_port" : 0,
         "type" : "tcp"
      },
      {
         "container_port" : 8088,
         "host_port" : 0,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : true,
      "enable_status_page" : true,
      "enable_web_page" : false
   },
   "use_host_network" : false,
   "volume_bindings" : []
}

**Comment by mbentley** [comment]
You didn't expose any of the ports it would appear.  Could you give me your run command?

**Comment by AlexanderSanchezNL** [comment]
Ehmmm, without sounding like a complete dumb*ss: I installed Docker, searched for Omada and installed your package. Then I clicked "Launch" and went into Advanced Settings where I enabled auto-restart. I didn't meddle with the Port Settings, they looked ok to me. And voilà, here we are :-)

So, I didn't run a run command script...

**Comment by mbentley** [comment]
Ah ok.  I am not familiar with how Synology packages up Docker containers but the gist of it is that the following ports need to be exposed from the container:

```
  -p 8088:8088 \
  -p 8043:8043 \
  -p 27001:27001/udp \
  -p 27002:27002 \
  -p 29810:29810/udp \
  -p 29811:29811 \
  -p 29812:29812 \
  -p 29813:29813 \
```

**Comment by AlexanderSanchezNL** [comment]
Yeah, I now figured as much... :-) Sorry.

I ran the following run command, and now it seems to be working:

docker run -d \
  --name omada-controller \
  --restart unless-stopped \
  -e TZ=Europe/Amsterdam \
  -e SMALL_FILES=false \
  -p 8088:8088 \
  -p 8043:8043 \
  -p 27001:27001/udp \
  -p 27002:27002 \
  -p 29810:29810/udp \
  -p 29811:29811 \
  -p 29812:29812 \
  -p 29813:29813 \
  -v omada-data:/opt/tplink/EAPController/data \
  -v omada-work:/opt/tplink/EAPController/work \
  -v omada-logs:/opt/tplink/EAPController/logs \
  mbentley/omada-controller:latest

**Comment by mbentley** [comment]
👍  Happy to help if you run into any other issues.
