### ISSUE TITLE
[Bug]: Reports exporting not working

### ISSUE THREAD

**Issue by danielponte** [mbentley/docker-omada-controller#446]
### Controller Version

v5.14.26

### Describe the Bug

Trying to export a report to PDF results in this error:

Failed to export report and possible reasons are:
1. Insufficient space. Please make sure your PC has the free memory space of over 1.2 GB.
2. Damaged software. It is recommended to reinstall the controller.
3. Privilege restriction of the file path. It is recommended to lift the privilege restriction first.

Exporting to .CSV is fine

### Expected Behavior

Download the PDF :)

### Steps to Reproduce

Go into the reports section and click on the top right icon to export

### How You're Launching the Container

```plain
Running exactly as the example on the site:


docker run -d \
  --name omada-controller \
  --stop-timeout 60 \
  --restart unless-stopped \
  --ulimit nofile=4096:8192 \
  -p 8088:8088 \
  -p 8043:8043 \
  -p 8843:8843 \
  -p 27001:27001/udp \
  -p 29810:29810/udp \
  -p 29811-29816:29811-29816 \
  -e MANAGE_HTTP_PORT=8088 \
  -e MANAGE_HTTPS_PORT=8043 \
  -e PGID="508" \
  -e PORTAL_HTTP_PORT=8088 \
  -e PORTAL_HTTPS_PORT=8843 \
  -e PORT_ADOPT_V1=29812 \
  -e PORT_APP_DISCOVERY=27001 \
  -e PORT_DISCOVERY=29810 \
  -e PORT_MANAGER_V1=29811 \
  -e PORT_MANAGER_V2=29814 \
  -e PORT_TRANSFER_V2=29815 \
  -e PORT_RTTY=29816 \
  -e PORT_UPGRADE_V1=29813 \
  -e PUID="508" \
  -e SHOW_SERVER_LOGS=true \
  -e SHOW_MONGODB_LOGS=false \
  -e SSL_CERT_NAME="tls.crt" \
  -e SSL_KEY_NAME="tls.key" \
  -e TZ=Etc/UTC \
  -v omada-data:/opt/tplink/EAPController/data \
  -v omada-logs:/opt/tplink/EAPController/logs \
  mbentley/omada-controller
```

### Container Logs

```plain
Nothing happens on the log when the UI spits out the error. Nada.
```

### MongoDB Logs

```plain
Same as omada log.
```

**Comment by mbentley** [comment]
You need to use the image with chromium as that is used the generate the PDFs.  See [the tags section of the README](https://github.com/mbentley/docker-omada-controller?tab=readme-ov-file#tags-with-chromium) as there is a specific tag.  It adds quite a bit of size to the image which is why there is a separate one.
