### ISSUE TITLE
Fails start, re-start loop

### ISSUE THREAD

**Issue by dougle03** [mbentley/docker-omada-controller#57]
Updated container on Synology NAS. Downloaded 'Latest' container
Followed additional instruction; Stopped container, cleared out existing folders (logs, work, data)
'Cleared' container, Restarted container, get the following in the log errors:

INFO: Time zone set to 'Europe/London'
INFO: Starting Omada Controller as user omada
error: exec: "/opt/tplink/EAPController/jre/bin/java": stat /opt/tplink/EAPController/jre/bin/java: no such file or directory
INFO: Time zone set to 'Europe/London'

And repeat!

I'm no expert so using the Docker GUI on DSM
Thanks,
![image](https://user-images.githubusercontent.com/59865048/87864296-79745f80-c95e-11ea-82ac-733940f9371a.png)

**Comment by mbentley** [comment]
How are you running the container?  Are you specifying your own command instead of relying on the default?  I'm assuming you're using the 4.1 image.  The JRE is no longer included in the installed bundle so it is installed in the system path.

**Comment by dougle03** [comment]
Hi, I'm an idiot on this!
Is below what you are refering to?
I'm using the DSM Docker GUI provided by synology ;(
![image](https://user-images.githubusercontent.com/59865048/87864399-b856e500-c95f-11ea-9f31-5c511711424e.png)

I've used the Docker registry within the Syno Docker GUI to download the 'Latest' image, so assume the latest tag is 4.1....?

**Comment by dougle03** [comment]
I don't think I have any control over the 'entry point' as above, it's pre-determined with the docker image I presume?

**Comment by mbentley** [comment]
Yes, latest is tagged to 4.1.  I'd suggest picking a version tag like 4.1 or 3.2 so you're locking yourself in on a version as I change out latest without notice. Especially in the case of 4.1, the breaking changes might be unexpected.

I'm not familiar with how Synology allows you to run containers but the 4.1 image has the correct entrypoint and command as defined in the Dockerfile.  I'll double check to make sure there isn't something funky going on with the auto builds on Hub though.

**Comment by dougle03** [comment]
Thanks. I was on 3.2.10, so might go back to that as I kept a copy of the v data folders

**Comment by mbentley** [comment]
I verified that the `latest` tag has the correct CMD and ENTRYPOINT:

```
# docker inspect docker.io/mbentley/omada-controller:latest --format '{{json .ContainerConfig.Entrypoint}}' | jq .
[
  "/entrypoint.sh"
]

# docker inspect docker.io/mbentley/omada-controller:latest --format '{{json .ContainerConfig.Cmd}}' | jq .
[
  "/bin/sh",
  "-c",
  "#(nop) ",
  "CMD [\"/usr/bin/java\" \"-server\" \"-Xms128m\" \"-Xmx1024m\" \"-XX:MaxHeapFreeRatio=60\" \"-XX:MinHeapFreeRatio=30\" \"-XX:+HeapDumpOnOutOfMemoryError\" \"-cp\" \"/opt/tplink/EAPController/lib/*:\" \"com.tplink.omada.start.OmadaLinuxMain\"]"
]
```

I'm wondering if the Synology inspects the entrypoint and command from the image when it is originally deployed and essentially overrides the entrypoint and command on the container.  It would have saved what was originally specified on the 3.2.x image as that's what I would expect for the older version.  At least that would explain the behavior.

**Comment by dougle03** [comment]
I manually attempted to update the container following the syno docker instructions:
download 'latest' container
Stop the container
'clear' the container
Start the container.

After doing the above I checked the logs and saw the comment about 4.1 being non-standard update, so then deleted the V folders and recreated them empty.
This got rid of the upgrade warnings, but then the JRE warning appeared.

since the synology does retain settings like volume maps and ports ect, it's possible it also retains the entrypoint too....?

**Comment by mbentley** [comment]
Sounds plausible.

**Comment by dougle03** [comment]
Would make sense, pitty, good job I've not got too many AP's to sort out! 
It's late now, I'll have another go in the morning when rested.
Might be worth adding a warning to Synology users about this? Especially the GUI syno docker users (Like me)...
Thanks Matt.
P
