### ISSUE TITLE
SSL certificate names

### ISSUE THREAD

**Issue by ulug79** [mbentley/docker-omada-controller#60]
Please add environment variables for customizing certificate names

**Comment by mbentley** [comment]
Just curious, what's the use case where the certificate names are an issue?

**Comment by ulug79** [comment]
I am using traefik 2.2 with letsencrypt certificate wildcard generation. A special container extracts the certificate in json format and puts them in a folder named cert.pem, fullchain.pem and key.pem

**Comment by ulug79** [comment]
at home i am using Unifi Controller container from https://hub.docker.com/r/jacobalberty/unifi

and in it you can set non-standard names through environment variables

**Comment by mbentley** [comment]
Are you expecting to just be able to update the certificate name or the whole path?

**Comment by ulug79** [comment]
For example in Unifi Controller i mount certficate folder as volume in container, In enviroment variable I just indicate the different name. Please create 2 environent variable for full chain name and key name. Thanks.

For example:
If your certificate or private key have different names, you can set the environment variables CERTNAME and CERT_PRIVATE_NAME to the name of your certificate/private key, e.g. CERTNAME=my-cert.pem and CERT_PRIVATE_NAME=my-privkey.pem.

**Comment by mbentley** [comment]
👍  Sounds good.  #61 should resolve this and add the ability to have custom names.
