### ISSUE TITLE
Unable to bind to cloud controller

### ISSUE THREAD

**Issue by mquestier1** [mbentley/docker-omada-controller#62]
When i want to bind the SDN Controller to the cloud Controller i get the message that the SDN controller is unable to connect to the server. In the logs i see the following error: 
2020-08-14 19:56:25 [qtp1807648168-70] [ERROR]-[SourceFile:848] - Apply deviceId failed, errorCode is -7111, msg is Cannot get response from server.

**Comment by mbentley** [comment]
That seems like a software issue.  I would suggest posting to https://community.tp-link.com/en/business/forum/582 as I am not sure what that would be referring to.  I'd suggest checking to see if you're doing any sort of ad blocking that could be interfering with the ability to communicate to the cloud service.
