### ISSUE TITLE
Ports for autodiscovery

### ISSUE THREAD

**Issue by xrs444** [mbentley/docker-omada-controller#66]
Hello, 

Using the following ports for my docker container I can automatically enroll devices using option 138 in DHCP using a Docker Swarm Overlay network, so no macvlan or host networking needed.

Tested by resetting my EAP245s and watching them re-enroll. My controller is in a separate VLAN so I can't test detection directly, but if it works with option 138 there's a good chance it will in the same subnet without.

    ports:
      - "29810:29810"
      - "29811:29811"
      - "29812:29812"
      - "29813:29813"
      - "29810:29810/udp"
      - "29811:29811/udp"
      - "29812:29812/udp"
      - "29813:29813/udp"
      - "8088:8088"
      - "8043:8043"
      - "8843:8843"

Not so much a an issue as a non-issue, but I hope that helps.

**Comment by mbentley** [comment]
Aha!  That would help explain why it works for some people but not everyone.  Thanks for that, I will try to verify what you mention and update the docs.  Thanks!
