### ISSUE TITLE
x86 Xpenology

### ISSUE THREAD

**Issue by jendrush** [mbentley/docker-omada-controller#67]
Is it possible to run software on x86 Xpenology Docker? I tried 4.1 version, and latest. Container showing me that it works, but i can't get acces over port 8088, 8843.

**Comment by mbentley** [comment]
I don't see why not.  That is going to completely depend on how you deploy containers using Xpenology.  It sounds like it either isn't exposing ports or something like that.

**Comment by jendrush** [comment]
Ports were the problem. Changed Bridge networking mode to Host to have full ports that Omada need, and it's working. Thank you.
