### ISSUE TITLE
Omada container default user and PW

### ISSUE THREAD

**Issue by keelhaulin** [mbentley/docker-omada-controller#71]
Thanks much for creating this container. I can access the login page but the documented TP-Link default user name and password (admin, admin) do not work. Are their different credentials in your image? I am using mbentley/omada-controller:3.2.1
![Image 246](https://user-images.githubusercontent.com/67303840/99856760-ad9f9d00-2b57-11eb-941b-bdc488531f51.png)

**Comment by mbentley** [comment]
There are no default credentials.  It should take you to the wizard on initial run.  If it doesn't, you have persistent data that exists.
![screenshot 2020-11-20 at 6 16 13 PM](https://user-images.githubusercontent.com/414445/99859034-e4c47d00-2b5c-11eb-8668-4efd32b758a7.png)

I would make sure to stop the container, clear the persistent data and start the container again.

**Comment by keelhaulin** [comment]
Thank you for the very quick response and pointing me in the right
direction. I found the install directories and removed them. I am using
Portainer and incorrectly assumed that deleting the container and image
would clear all persistent data. I have it working now after deploying a
fresh container.

Thanks much for the original effort and the timely support

**Comment by mbentley** [comment]
Good to hear, happy to help!
