### ISSUE TITLE
Captive Portal?

### ISSUE THREAD

**Issue by bntsp** [mbentley/docker-omada-controller#76]
How do i get the captive portal to work?

It is running on port 8089. Do i have to open the ports somehow?

Sorry for asking, but i am not so much into docker.

**Comment by mbentley** [comment]
How did you run the container?  The `PORTAL_HTTP_PORT` env var when you first run the container should set the value fo the captive portal port, otherwise you need to set it via the UI after first run.  How you need to expose the port would depend on how you ran the portal.

**Comment by mbentley** [comment]
Closing issue.  Let me know if you have further issues.
