### ISSUE TITLE
Controller Mail Server

### ISSUE THREAD

**Issue by Kirk-GH** [mbentley/docker-omada-controller#82]
Hi,

First off.  Great work and thank you very much.

Secondly, is it possible for the mail server settings in the controller to send email notifications?  I have put in the same settings as I have in my nas which works just fine.

Any assistance would be grateful.

Thanks,
Kirk

**Comment by mbentley** [comment]
Thanks!  Yes, email works as one would expect.  If there are any mail failures, you might want to check to see if there are any rules that would prevent email coming from a container that could show up against an ACL as an IP address that isn't allowed or anything like that related to the controller running in a container.

<img width="683" alt="screenshot 2021-01-19 at 8 53 06 PM" src="https://user-images.githubusercontent.com/414445/105116252-5dca4d00-5a98-11eb-9391-ceeaa1862cc6.png">
<img width="462" alt="screenshot 2021-01-19 at 8 52 39 PM" src="https://user-images.githubusercontent.com/414445/105116254-5e62e380-5a98-11eb-8ba2-12fb91d525c8.png">

**Comment by Kirk-GH** [comment]
Thanks for the prompt response.  I did fail to mention that I am running the container in my Synology nas.  Are there maybe some environment variables I would have to include?

**Comment by mbentley** [comment]
I do not know how your mail server is configured to send mail but there shouldn't be anything special about Omada Controller running in a container in terms of how to setup mail.

**Comment by Kirk-GH** [comment]
Hi.  Here are my settings for nas and for Omada.  There is no access control list that I know of.

Nas Settings
![nas settings](https://user-images.githubusercontent.com/77707562/105119756-f8c62580-5a9e-11eb-9ceb-81cccb9e48fd.png)

Omada Settings
![omada settings](https://user-images.githubusercontent.com/77707562/105119810-109da980-5a9f-11eb-995e-917a0989c7ab.png)

Thanks again,
Kirk

**Comment by mbentley** [comment]
Check the logs of the omada controller container.  It will output detail information about what is happening with the SMTP test.  Are you filling in a `Sender Address`?

**Comment by Kirk-GH** [comment]
I'm new to Docker.  Totally forgot about the logs.  Thanks.  I have tried with the sender address entered and also not.

![image](https://user-images.githubusercontent.com/77707562/105122289-ef8b8780-5aa3-11eb-968f-762fdc04833d.png)

Kirk

**Comment by mbentley** [comment]
Are you sure that your Synology settings are correct?  Normally SMTP over TLS/SSL is 465 or 587 although I suppose they could be listening over TLS on 25. I'm on my phone or I'd check by doing a test connection.

**Comment by Kirk-GH** [comment]
Totally agree with you.  These values work for my nas settings.

![image](https://user-images.githubusercontent.com/77707562/105123036-5a898e00-5aa5-11eb-8194-c257258c9035.png)

**Comment by Kirk-GH** [comment]
Ok, well, no worries.  I'll keep at it.  I don't mean to take up too much of your time.

I really appreciate you assisting.  I'll post back once I figure it out.

Kirk

**Comment by mbentley** [comment]
Yeah, I would try using port `587` with SSL and see how that works out for you.  I did some more poking around and I was able to get the same error message when I ticked the SSL box when I was connecting to a non-TLS/SSL enabled port but that doesn't match the instructions on the screen shot from Bell but I suppose that wouldn't be the first time documentation wasn't completely correct and I also wouldn't put it past the TP-Link team to have implemented something funny in how SMTP works.  I don't have a TLS enabled mail server here locally otherwise I would test that as well.

**Comment by Kirk-GH** [comment]
Ya, I tried all different ports already.  25, 465, 587, etc.  As I said, it works coming directly from my nas with the same/proper setup.  It really has to be something about not getting out of the docker.  I have no problem giving you my email credentials should you feel you want to do some testing.

**Comment by Kirk-GH** [comment]
Well, as you said, something funny.  I unchecked SSL and it sent.  Probably should have tried that before but why would I if it works as expected with SSL from other applications.

I'm really sorry for wasting so much of your time.  Hopefully this can be helpful (try the unexpected) to anyone else searching.

I appreciated your prompt responses and again thank you for your work.

**Comment by mbentley** [comment]
There are some other comments on some oddities of the SMTP implementation over on the [TP-Link forums](https://community.tp-link.com/en/business/forum/topic/217556) as well where they mention the issues with StartTLS not working properly.

**Comment by kylaris** [comment]
I fixed this issue by opening up the Synology firewall on port 465 / docker IP
