### ISSUE TITLE
Unable to connect to Omada

### ISSUE THREAD

**Issue by RogerMCT** [mbentley/docker-omada-controller#85]
I'm stuck.  I have tried several times to deploy this docker but I can't connect to it using the host 192.168.1.1 or localhost ON the host. 

This is running on Windows 10 using Docker Desktop.  Firewall is turned off on the host machine.

My Command:
docker run -d --name Omada-Controller --restart unless-stopped --net host -e MANAGE_HTTP_PORT=8088 -e MANAGE_HTTPS_PORT=8043 -e PORTAL_HTTP_PORT=8088 -e PORTAL_HTTPS_PORT=8843  -e SHOW_SERVER_LOGS=true -e SHOW_MONGODB_LOGS=false -e TZ=America/Indianapolis -v $HOME/docker/omada/data:/opt/tplink/EAPController/data -v $HOME/docker/omada/work:/opt/tplink/EAPController/work -v $HOME/docker/omada/logs:/opt/tplink/EAPController/logs mbentley/omada-controller:latest
![Screenshot 2021-02-16 185910](https://user-images.githubusercontent.com/13243482/108137030-162fe480-7089-11eb-87f0-7ff666a8d33a.jpg)
![Screenshot 2021-02-16 190003](https://user-images.githubusercontent.com/13243482/108137126-46778300-7089-11eb-9803-9cd69f3ad47e.jpg)
![Screenshot 2021-02-16 190024](https://user-images.githubusercontent.com/13243482/108137127-47101980-7089-11eb-937b-4abddcdcc0e8.jpg)

**Comment by mbentley** [comment]
Are you trying the IP or localhost on 8088 via http? or https on 8043?

**Comment by RogerMCT** [comment]
I have tried the host IP and those ports and localhost with those ports.  I have two other images running (minecraft, and terraria) successfully, but I'm unable to access this one.  If you would like to hope in and take a look, I can set that up.

**Comment by mbentley** [comment]
Are the others running net=host?

**Comment by RogerMCT** [comment]
No, Minecrasft is -p=25565 and Terreria is -p=7777

**Comment by mbentley** [comment]
Give this a shot:

```
docker run -d --name Omada-Controller --restart unless-stopped -p 29810:29810 -p 29811:29811 -p 29812:29812 -p 29813:29813 -p 29810:29810/udp -p 29811:29811/udp -p 29812:29812/udp -p 29813:29813/udp -p 8088:8088 -p 8043:8043 -p 8843:8843 -e MANAGE_HTTP_PORT=8088 -e MANAGE_HTTPS_PORT=8043 -e PORTAL_HTTP_PORT=8088 -e PORTAL_HTTPS_PORT=8843 -e SHOW_SERVER_LOGS=true -e SHOW_MONGODB_LOGS=false -e TZ=America/Indianapolis -v $HOME/docker/omada/data:/opt/tplink/EAPController/data -v $HOME/docker/omada/work:/opt/tplink/EAPController/work -v $HOME/docker/omada/logs:/opt/tplink/EAPController/logs mbentley/omada-controller:latest
```

**Comment by RogerMCT** [comment]
THAT WORKED PERFECT, and it found my access points (I need to update their firmware).  YOU ROCK MBENTLEY!!
![Capture](https://user-images.githubusercontent.com/13243482/108143376-9ceabe80-7095-11eb-8901-67035ce80479.PNG)

**Comment by mbentley** [comment]
Awesome, glad to hear it works!
