### ISSUE TITLE
Health Check doesn't work with different MANAGE_HTTPS_PORT

### ISSUE THREAD

**Issue by pianomansam** [mbentley/docker-omada-controller#87]
If I use a different MANAGE_HTTPS_PORT environment variable value other than 8043, the docker health check fails. This is because the port is hardcoded.

https://github.com/mbentley/docker-omada-controller/blob/master/Dockerfile.v4.2.x#L20

Would it be possible to write a small shell script that uses whatever is set in MANAGE_HTTPS_PORT?

**Comment by mbentley** [comment]
Good catch!  Fixed via #88
